//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyMSlideManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyMSlideManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string ANSWER_CANCEL {
            get {
                return ResourceManager.GetString("ANSWER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string ANSWER_NO {
            get {
                return ResourceManager.GetString("ANSWER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string ANSWER_YES {
            get {
                return ResourceManager.GetString("ANSWER_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto play.
        /// </summary>
        public static string AUTO_PLAY {
            get {
                return ResourceManager.GetString("AUTO_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        public static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade in.
        /// </summary>
        public static string FADE_IN_FORWARD {
            get {
                return ResourceManager.GetString("FADE_IN_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade in (reversing).
        /// </summary>
        public static string FADE_IN_REVERSE {
            get {
                return ResourceManager.GetString("FADE_IN_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade out.
        /// </summary>
        public static string FADE_OUT_FORWARD {
            get {
                return ResourceManager.GetString("FADE_OUT_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade out (reversing).
        /// </summary>
        public static string FADE_OUT_REVERSE {
            get {
                return ResourceManager.GetString("FADE_OUT_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flower {
            get {
                object obj = ResourceManager.GetObject("flower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string LOOP {
            get {
                return ResourceManager.GetString("LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New slideshow.
        /// </summary>
        public static string NEW_SLIDESHOW {
            get {
                return ResourceManager.GetString("NEW_SLIDESHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open slideshow.
        /// </summary>
        public static string OPEN_SLIDESHOW {
            get {
                return ResourceManager.GetString("OPEN_SLIDESHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Slideshow.
        /// </summary>
        public static string OPEN_SLIDESHOW_TITLE {
            get {
                return ResourceManager.GetString("OPEN_SLIDESHOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save slideshow.
        /// </summary>
        public static string SAVE_SLIDESHOW {
            get {
                return ResourceManager.GetString("SAVE_SLIDESHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save slideshow as....
        /// </summary>
        public static string SAVE_SLIDESHOW_AS {
            get {
                return ResourceManager.GetString("SAVE_SLIDESHOW_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Slideshow.
        /// </summary>
        public static string SAVE_SLIDESHOW_TITLE {
            get {
                return ResourceManager.GetString("SAVE_SLIDESHOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow file.
        /// </summary>
        public static string SLIDESHOW_FILE {
            get {
                return ResourceManager.GetString("SLIDESHOW_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slideshow has changed. Do you want to save it?.
        /// </summary>
        public static string WANT_TO_SAVE {
            get {
                return ResourceManager.GetString("WANT_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string WANT_TO_SAVE_TITLE {
            get {
                return ResourceManager.GetString("WANT_TO_SAVE_TITLE", resourceCulture);
            }
        }
    }
}
