files:
  - source: /OnlyM/Properties/Resources.resx
    translation: /OnlyM/Properties/%file_name%.%locale%.resx
  - source: /OnlyM.Core/Properties/Resources.resx
    translation: /OnlyM.Core/Properties/%file_name%.%locale%.resx
