//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow pause.
        /// </summary>
        public static string ALLOW_PAUSE {
            get {
                return ResourceManager.GetString("ALLOW_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow scrubbing when paused.
        /// </summary>
        public static string ALLOW_SCRUB {
            get {
                return ResourceManager.GetString("ALLOW_SCRUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow position seeking.
        /// </summary>
        public static string ALLOW_SEEK {
            get {
                return ResourceManager.GetString("ALLOW_SEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyM software version: {0}.
        /// </summary>
        public static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-rotate.
        /// </summary>
        public static string AUTO_ROTATE {
            get {
                return ResourceManager.GetString("AUTO_ROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Screen.
        /// </summary>
        public static string BLANK_SCREEN {
            get {
                return ResourceManager.GetString("BLANK_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string BOTTOM_CHAR {
            get {
                return ResourceManager.GetString("BOTTOM_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache images (better performance but more memory).
        /// </summary>
        public static string CACHE_IMAGES {
            get {
                return ResourceManager.GetString("CACHE_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm when stopping.
        /// </summary>
        public static string CONFIRM_STOP {
            get {
                return ResourceManager.GetString("CONFIRM_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop playback?.
        /// </summary>
        public static string CONFIRM_STOP_MEDIA {
            get {
                return ResourceManager.GetString("CONFIRM_STOP_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (contains {0} rolling slides).
        /// </summary>
        public static string CONTAINS_X_ROLLING_SLIDES {
            get {
                return ResourceManager.GetString("CONTAINS_X_ROLLING_SLIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (contains {0} slides).
        /// </summary>
        public static string CONTAINS_X_SLIDES {
            get {
                return ResourceManager.GetString("CONTAINS_X_SLIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error!.
        /// </summary>
        public static string COPYING_ERROR {
            get {
                return ResourceManager.GetString("COPYING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date.
        /// </summary>
        public static string CURRENT_DATE {
            get {
                return ResourceManager.GetString("CURRENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display help.
        /// </summary>
        public static string DISPLAY_HELP {
            get {
                return ResourceManager.GetString("DISPLAY_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your media files here!.
        /// </summary>
        public static string DROP_HERE {
            get {
                return ResourceManager.GetString("DROP_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fading speed.
        /// </summary>
        public static string FADING_SPEED {
            get {
                return ResourceManager.GetString("FADING_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fading style.
        /// </summary>
        public static string FADING_STYLE {
            get {
                return ResourceManager.GetString("FADING_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied.
        /// </summary>
        public static string FILE_COPIED {
            get {
                return ResourceManager.GetString("FILE_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files copied.
        /// </summary>
        public static string FILES_COPIED {
            get {
                return ResourceManager.GetString("FILES_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open media folder.
        /// </summary>
        public static string FOLDER {
            get {
                return ResourceManager.GetString("FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media folder disabled by administrator!.
        /// </summary>
        public static string FOLDER_DISABLED {
            get {
                return ResourceManager.GetString("FOLDER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        public static string FREEZE {
            get {
                return ResourceManager.GetString("FREEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIDE.
        /// </summary>
        public static string HIDE {
            get {
                return ResourceManager.GetString("HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Margins.
        /// </summary>
        public static string IMAGE_MARGINS {
            get {
                return ResourceManager.GetString("IMAGE_MARGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include &quot;Blank Screen&quot; item.
        /// </summary>
        public static string INCLUDE_BLANK {
            get {
                return ResourceManager.GetString("INCLUDE_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JW Library compatibility mode.
        /// </summary>
        public static string JW_COMPAT_MODE {
            get {
                return ResourceManager.GetString("JW_COMPAT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string LEFT_CHAR {
            get {
                return ResourceManager.GetString("LEFT_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        public static string LOGGING_LEVEL {
            get {
                return ResourceManager.GetString("LOGGING_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of items.
        /// </summary>
        public static string MAX_ITEMS {
            get {
                return ResourceManager.GetString("MAX_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media is active - cannot close!.
        /// </summary>
        public static string MEDIA_ACTIVE {
            get {
                return ResourceManager.GetString("MEDIA_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media folder.
        /// </summary>
        public static string MEDIA_FOLDER {
            get {
                return ResourceManager.GetString("MEDIA_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Media Folder.
        /// </summary>
        public static string MEDIA_FOLDER_BROWSE {
            get {
                return ResourceManager.GetString("MEDIA_FOLDER_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media folder specified on command-line:.
        /// </summary>
        public static string MEDIA_FOLDER_CMDLINE {
            get {
                return ResourceManager.GetString("MEDIA_FOLDER_CMDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media monitor.
        /// </summary>
        public static string MEDIA_MONITOR {
            get {
                return ResourceManager.GetString("MEDIA_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media page.
        /// </summary>
        public static string MEDIA_PAGE {
            get {
                return ResourceManager.GetString("MEDIA_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MONITOR_NONE {
            get {
                return ResourceManager.GetString("MONITOR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available!.
        /// </summary>
        public static string NEW_UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("NEW_UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string NEW_VERSION {
            get {
                return ResourceManager.GetString("NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deselect monitor when media is active.
        /// </summary>
        public static string NO_DESELECT_MONITOR {
            get {
                return ResourceManager.GetString("NO_DESELECT_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported media files!.
        /// </summary>
        public static string NO_SUPPORTED_FILES {
            get {
                return ResourceManager.GetString("NO_SUPPORTED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window always on top.
        /// </summary>
        public static string ON_TOP {
            get {
                return ResourceManager.GetString("ON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause on final frame.
        /// </summary>
        public static string PAUSE_FINAL_FRAME {
            get {
                return ResourceManager.GetString("PAUSE_FINAL_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent backdrop.
        /// </summary>
        public static string PERMANENT_BACKDROP {
            get {
                return ResourceManager.GetString("PERMANENT_BACKDROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURGE THUMBNAIL CACHE.
        /// </summary>
        public static string PURGE_THUMBS {
            get {
                return ResourceManager.GetString("PURGE_THUMBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering engine.
        /// </summary>
        public static string RENDERING_ENGINE {
            get {
                return ResourceManager.GetString("RENDERING_ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string RIGHT_CHAR {
            get {
                return ResourceManager.GetString("RIGHT_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rolling slide {0} of {1}.
        /// </summary>
        public static string ROLLING_SLIDE_X_OF_Y {
            get {
                return ResourceManager.GetString("ROLLING_SLIDE_X_OF_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY.
        /// </summary>
        public static string SECTION_DISPLAY {
            get {
                return ResourceManager.GetString("SECTION_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGES.
        /// </summary>
        public static string SECTION_IMAGES {
            get {
                return ResourceManager.GetString("SECTION_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARGINS (as percentage of screen size).
        /// </summary>
        public static string SECTION_MARGINS {
            get {
                return ResourceManager.GetString("SECTION_MARGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIA FILES.
        /// </summary>
        public static string SECTION_MEDIA_FILES {
            get {
                return ResourceManager.GetString("SECTION_MEDIA_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISCELLANEOUS.
        /// </summary>
        public static string SECTION_MISC {
            get {
                return ResourceManager.GetString("SECTION_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEOS &amp; AUDIO.
        /// </summary>
        public static string SECTION_VIDEO_AUDIO {
            get {
                return ResourceManager.GetString("SECTION_VIDEO_AUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings disabled by administrator!.
        /// </summary>
        public static string SETTINGS_DISABLED {
            get {
                return ResourceManager.GetString("SETTINGS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;Freeze&apos; command in Command Panel.
        /// </summary>
        public static string SHOW_FREEZE {
            get {
                return ResourceManager.GetString("SHOW_FREEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show subtitles if available.
        /// </summary>
        public static string SHOW_SUBTITLES {
            get {
                return ResourceManager.GetString("SHOW_SUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slide {0} of {1}.
        /// </summary>
        public static string SLIDE_X_OF_Y {
            get {
                return ResourceManager.GetString("SLIDE_X_OF_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string TOP_CHAR {
            get {
                return ResourceManager.GetString("TOP_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide.
        /// </summary>
        public static string UNHIDE {
            get {
                return ResourceManager.GetString("UNHIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Command Panel.
        /// </summary>
        public static string USE_CMD_PANEL {
            get {
                return ResourceManager.GetString("USE_CMD_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use embedded thumbnails where available.
        /// </summary>
        public static string USE_THUMBS {
            get {
                return ResourceManager.GetString("USE_THUMBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use embedded titles where available.
        /// </summary>
        public static string USE_TITLES {
            get {
                return ResourceManager.GetString("USE_TITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Margins.
        /// </summary>
        public static string VIDEO_MARGINS {
            get {
                return ResourceManager.GetString("VIDEO_MARGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will pause on final frame.
        /// </summary>
        public static string WILL_PAUSE {
            get {
                return ResourceManager.GetString("WILL_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
