//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyM software version: {0}.
        /// </summary>
        internal static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Screen.
        /// </summary>
        internal static string BLANK_SCREEN {
            get {
                return ResourceManager.GetString("BLANK_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop playback?.
        /// </summary>
        internal static string CONFIRM_STOP_MEDIA {
            get {
                return ResourceManager.GetString("CONFIRM_STOP_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error!.
        /// </summary>
        internal static string COPYING_ERROR {
            get {
                return ResourceManager.GetString("COPYING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied.
        /// </summary>
        internal static string FILE_COPIED {
            get {
                return ResourceManager.GetString("FILE_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files copied.
        /// </summary>
        internal static string FILES_COPIED {
            get {
                return ResourceManager.GetString("FILES_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open media folder.
        /// </summary>
        internal static string FOLDER {
            get {
                return ResourceManager.GetString("FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media folder disabled by administrator!.
        /// </summary>
        internal static string FOLDER_DISABLED {
            get {
                return ResourceManager.GetString("FOLDER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media is active - cannot close!.
        /// </summary>
        internal static string MEDIA_ACTIVE {
            get {
                return ResourceManager.GetString("MEDIA_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Media Folder.
        /// </summary>
        internal static string MEDIA_FOLDER_BROWSE {
            get {
                return ResourceManager.GetString("MEDIA_FOLDER_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MONITOR_NONE {
            get {
                return ResourceManager.GetString("MONITOR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available!.
        /// </summary>
        internal static string NEW_UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("NEW_UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deselect monitor when media is active.
        /// </summary>
        internal static string NO_DESELECT_MONITOR {
            get {
                return ResourceManager.GetString("NO_DESELECT_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported media files!.
        /// </summary>
        internal static string NO_SUPPORTED_FILES {
            get {
                return ResourceManager.GetString("NO_SUPPORTED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings disabled by administrator!.
        /// </summary>
        internal static string SETTINGS_DISABLED {
            get {
                return ResourceManager.GetString("SETTINGS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
