//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyM.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyM.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Audio {
            get {
                object obj = ResourceManager.GetObject("Audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        internal static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfade.
        /// </summary>
        internal static string FADE_CROSS {
            get {
                return ResourceManager.GetString("FADE_CROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade in.
        /// </summary>
        internal static string FADE_IN {
            get {
                return ResourceManager.GetString("FADE_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade in and out.
        /// </summary>
        internal static string FADE_IN_OUT {
            get {
                return ResourceManager.GetString("FADE_IN_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string FADE_NONE {
            get {
                return ResourceManager.GetString("FADE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade out.
        /// </summary>
        internal static string FADE_OUT {
            get {
                return ResourceManager.GetString("FADE_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string FADE_SPEED_FAST {
            get {
                return ResourceManager.GetString("FADE_SPEED_FAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FADE_SPEED_NORMAL {
            get {
                return ResourceManager.GetString("FADE_SPEED_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string FADE_SPEED_SLOW {
            get {
                return ResourceManager.GetString("FADE_SPEED_SLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super fast.
        /// </summary>
        internal static string FADE_SPEED_SUPER_FAST {
            get {
                return ResourceManager.GetString("FADE_SPEED_SUPER_FAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string LOG_LEVEL_DEBUG {
            get {
                return ResourceManager.GetString("LOG_LEVEL_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LOG_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        internal static string LOG_LEVEL_FATAL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string LOG_LEVEL_INFORMATION {
            get {
                return ResourceManager.GetString("LOG_LEVEL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string LOG_LEVEL_VERBOSE {
            get {
                return ResourceManager.GetString("LOG_LEVEL_VERBOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LOG_LEVEL_WARNING {
            get {
                return ResourceManager.GetString("LOG_LEVEL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string MAGNIFIER_SHAPE_CIRCLE {
            get {
                return ResourceManager.GetString("MAGNIFIER_SHAPE_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string MAGNIFIER_SHAPE_SQUARE {
            get {
                return ResourceManager.GetString("MAGNIFIER_SHAPE_SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string MAGNIFIER_SIZE_LARGE {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MAGNIFIER_SIZE_MEDIUM {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string MAGNIFIER_SIZE_SMALL {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Large.
        /// </summary>
        internal static string MAGNIFIER_SIZE_XLARGE {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_XLARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Small.
        /// </summary>
        internal static string MAGNIFIER_SIZE_XSMALL {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_XSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX Large.
        /// </summary>
        internal static string MAGNIFIER_SIZE_XXLARGE {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_XXLARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX Small.
        /// </summary>
        internal static string MAGNIFIER_SIZE_XXSMALL {
            get {
                return ResourceManager.GetString("MAGNIFIER_SIZE_XXSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PDF {
            get {
                object obj = ResourceManager.GetObject("PDF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unknown {
            get {
                object obj = ResourceManager.GetObject("Unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Web {
            get {
                object obj = ResourceManager.GetObject("Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
